### ISSUE TITLE
depricated usage of express-session

### ISSUE THREAD

**Issue by nurettinbakkal** [matthewbdaly/babblr#1]
When i run node index.js, i get the error below:

express-session deprecated undefined resave option; provide resave option index.js:31:21
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option index.js:31:21

Found and fixed the issue on my local. You can find the patch below:

diff --git a/index.js b/index.js
index fbdf0e5..5428073 100644
--- a/index.js
+++ b/index.js
@@ -32,7 +32,9 @@ sessionMiddleware = session({
     store: new RedisStore({
         client: client
     }),
-    secret: 'blibble'
-    secret: 'blibble',
-    resave: true,
-    saveUninitialized: true
  });
  app.use(sessionMiddleware);

**Comment by matthewbdaly** [comment]
Please could you submit a pull request for this? That way Travis CI will build it and we'll be able to see if any problems occur before merging it.
